spring:
  datasource:
    url: jdbc:mysql://localhost:3306/consistency-task?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000

consistency:
  task:
    parallel:
      pool:
        thread-max-pool-size: 6
        thread-core-pool-size: 6
        thread-pool-keep-alive-time: 60
        thread-pool-keep-alive-time-unit: SECONDS
        thread-pool-queue-size: 200
        # 框架自身有默认的实现类 来扫描查询任务的开始时间以及结束时间架自身有默认的实现类
        #来扫描查询任务的开始时间以及结束时间，这里给出定制化的实现类，这里给出定制化的实现类
        #task-schedule-time-range-class-name:xxx.xxx.MyTaskTimeRangeQuery
    action:
      fail-count-threshold: 0
    shard:
      task-sharded: false