CREATE TABLE `consistency_task`
(
    `id`                     bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键⾃增',
    `task_id`                varchar(500) NOT NULL COMMENT '用户自定义的任务名称，如果没有则使方案法签名',
    `task_status`            int(11) NOT NULL DEFAULT '0' COMMENT '执行状态， 0：初始化, 1：开始执行, 2： 执行失败, 3：执行成功',
    `execute_times`          int(11) NOT NULL COMMENT '执行次数',
    `execute_time`           bigint(20) NOT NULL COMMENT '执行时间',
    `parameter_types`        varchar(255) NOT NULL COMMENT '参数的类路径名称',
    `method_name`            varchar(100) NOT NULL COMMENT '方法名',
    `method_sign_name`       varchar(200) NOT NULL DEFAULT '' COMMENT '方法签名',
    `execute_interval_sec`   int(11) NOT NULL DEFAULT '60' COMMENT '执行间隔秒',
    `delay_time`             int(11) NOT NULL DEFAULT '60' COMMENT '延迟时间：单位秒',
    `task_parameter`         varchar(200) NOT NULL DEFAULT '' COMMENT '任务参数',
    `performance_way`        int(11) NOT NULL COMMENT '执行模式：1、立即执行 2、调度执行',
    `thread_way`             int(11) NOT NULL COMMENT '线程模型 1、异步 2、同步',
    `error_msg`              varchar(200) NOT NULL DEFAULT '' COMMENT '执行的error信息',
    `alert_expression`       varchar(100)          DEFAULT NULL COMMENT '告警表达式',
    `alert_action_bean_name` varchar(255)          DEFAULT NULL COMMENT '告警逻辑的的执行beanName',
    `fallback_class_name`    varchar(255)          DEFAULT NULL COMMENT '降级逻辑的的类路径',
    `fallback_error_msg`     varchar(200)          DEFAULT NULL COMMENT '降级失败时的错误信息',
    `shard_key`              bigint(20) NOT NULL DEFAULT '0' COMMENT '任务分片键',
    `created_time`           datetime     NOT NULL COMMENT '创建时间',
    `updated_time`           datetime     NOT NULL COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4;